sudo: required
services:
        - docker

before_install:
        - docker build -t subrota/docker-react -f Dockerfile.dev .

script:
        - docker run subrota/docker-react npm run test -- --coverage 
